version: 0.2

phases:
  first_phase:
    commands:
      - npm install first phase
      - npm install second command
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
